#!/usr/bin/env tsx
import { readFileSync } from "node:fs";

import {
  CHANNEL_DELIVERY_EVENTS,
  CHANNEL_DELIVERY_STATES,
  CHANNEL_NOTICE_STATES,
  renderChannelDeliveryMermaid,
} from "@/shared/channel-delivery";

const docPath = "docs/channel-delivery-state-machine.md";
const governancePath =
  "docs/adr/0001-channel-delivery-state-machine-source.md";

const expectedMermaidBlock = [
  "<!-- Generated by scripts/render-channel-delivery-diagram.ts -->",
  "<!-- Source: src/shared/channel-delivery.ts -->",
  "```mermaid",
  renderChannelDeliveryMermaid().trimEnd(),
  "```",
].join("\n");

const doc = readFileSync(docPath, "utf8");
const governance = readFileSync(governancePath, "utf8");
if (
  !governance.includes("src/shared/channel-delivery.ts") ||
  !governance.includes("docs/channel-delivery-state-machine.md") ||
  !governance.includes("HOSTED_DELIVERY_CHANNEL_NAMES")
) {
  throw new Error(
    `${governancePath} must name the runtime source, generated artifact, and hosted-delivery boundary.`,
  );
}
if (!doc.includes(expectedMermaidBlock)) {
  throw new Error(
    `${docPath} is stale. Run: pnpm exec tsx scripts/render-channel-delivery-diagram.ts`,
  );
}

const missing = [
  ...CHANNEL_DELIVERY_STATES,
  ...CHANNEL_NOTICE_STATES,
  ...CHANNEL_DELIVERY_EVENTS,
].filter((value) => !doc.includes(value));

if (missing.length > 0) {
  throw new Error(`${docPath} is missing channel delivery terms: ${missing.join(", ")}`);
}
